#!/usr/bin/env python3
"""Generate pages64 panel SVGs from layout specs (PANELS, below).

Draws the shared panel grammar (CLAUDE.md "Panel structure") for any width:
background, accent trapezoid between the screw zones, title (Montserrat Bold
name + Light "64", cap 4.125 mm, cap top at 7 mm), bottom rule and the domino
logo centered above it. A spec adds the body: jacks with their labels (output
= badge under the jack, input = plain text under the jack), separators, and a
gesture legend. Text is emitted as glyph paths (NanoSVG cannot render <text>),
through gen_title_paths.py's NanoVG-safe pipeline.

Jack positions in a spec are the jack *centers*, the same numbers the widget
code passes to mm2px(Vec(x, y)); keep the two in sync and check the result
with tools/panel_audit/panel_audit.py.

Usage (from the repo root, in the project venv):
    .venv/bin/python tools/gen_panel.py Step64 [...]      # writes res/<Name>.svg
Fonts: Montserrat Bold and Light, vendored in tools/fonts/ (SIL OFL 1.1, see
tools/fonts/OFL.txt); $PAGES64_FONTS overrides the folder.
"""
import os
import sys

from fontTools.ttLib import TTFont

sys.path.insert(0, os.path.dirname(__file__))
from gen_title_paths import glyph_to_svg_d, glyph_advance, text_width  # noqa: E402

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
FONT_DIR = os.environ.get("PAGES64_FONTS", os.path.join(os.path.dirname(__file__), "fonts"))

HP = 5.08
H = 128.5
BG, TEXT = "#1e1e1e", "#d0d0d0"
ACCENT = {"page": "#f26522", "companion": "#22aff2"}

TITLE_CAP, TITLE_TOP = 4.125, 7.0   # cap height, cap top y
TITLE_EDGE = 1.0          # a title that doesn't fit at TITLE_CAP shrinks to this margin
OUTER_SCREWS_MAX_HP = 6   # P64::addScrews: screws in the first/last HP up to here
TRAPEZOID_SLOPE = 2.48    # horizontal run of each trapezoid slope
TRAPEZOID_MIN_BOTTOM = 5.2  # narrowest bottom edge (a 4HP panel inset by 1HP)
LABEL_CAP = 2.0
BADGE_W, BADGE_H, BADGE_RX = 11.0, 3.5, 1.0
LABEL_DY = 7.0            # label center below the jack center
LEGEND_CAP, LEGEND_PITCH = 1.6, 3.4
EDGE = 0.8                # text must stay this far inside the panel


class Fonts:
    def __init__(self):
        self.faces = {}
        for weight in ("bold", "light"):
            path = os.path.join(FONT_DIR, "Montserrat-%s.ttf" % weight.capitalize())
            font = TTFont(path)
            self.faces[weight] = (font, font.getGlyphSet(), font.getBestCmap(),
                                  font["OS/2"].sCapHeight)

    def width(self, segments, cap):
        w = 0.0
        for text, weight in segments:
            font, gs, cmap, capu = self.faces[weight]
            w += text_width(font, text, cap / capu)
        return w

    def paths(self, segments, x, baseline, cap, color):
        """Glyph paths for segments [(text, weight)], starting at x."""
        out = []
        for text, weight in segments:
            font, gs, cmap, capu = self.faces[weight]
            scale = cap / capu
            for ch in text:
                if ord(ch) not in cmap:
                    continue
                g = cmap[ord(ch)]
                d = glyph_to_svg_d(gs, g, scale, x, baseline)
                if d:
                    out.append('<path fill="%s" fill-rule="evenodd" d="%s"/>' % (color, d))
                x += glyph_advance(gs, g, scale)
        return out


def build(name, spec, fonts):
    W = spec["hp"] * HP
    accent = ACCENT[spec.get("kind", "page")]
    svg = []
    add = svg.append

    def text(segments, x, baseline, cap, color, align, what):
        w = fonts.width(segments, cap)
        x0 = {"center": x - w / 2, "left": x, "right": x - w}[align]
        if x0 < EDGE - 1e-6 or x0 + w > W - EDGE + 1e-6:
            raise SystemExit("%s: %s is %.1f mm wide and doesn't fit (x %.1f–%.1f, panel %.2f)"
                             % (name, what, w, x0, x0 + w, W))
        svg.extend("  " + p for p in fonts.paths(segments, x0, baseline, cap, color))

    add('<?xml version="1.0" encoding="UTF-8"?>')
    add('<svg xmlns="http://www.w3.org/2000/svg"')
    add('     width="%gmm" height="%gmm"' % (round(W, 2), H))
    add('     viewBox="0 0 %g %g">' % (round(W, 2), H))
    add('  <!-- generated by tools/gen_panel.py; edit the spec, not this file -->')
    add('  <rect width="%g" height="%g" fill="%s"/>' % (round(W, 2), H, BG))

    # accent trapezoid and the bottom rule. With corner screws (narrow panels)
    # the trapezoid starts at 1.5HP, halfway between the screw zone and the
    # wide panels' 2HP, so its slopes keep clear of the screws; on the
    # narrowest panels it moves out further so its bottom edge stays at least
    # TRAPEZOID_MIN_BOTTOM wide instead of collapsing into a triangle (4HP:
    # 1HP, slopes close to the screws).
    x0 = (1.5 if spec["hp"] <= OUTER_SCREWS_MAX_HP else 2) * HP
    x0 = min(x0, (W - TRAPEZOID_MIN_BOTTOM) / 2 - TRAPEZOID_SLOPE)
    x1 = W - x0
    add('  <polygon points="0,0 %.2f,0 %.2f,0.5 %.2f,0.5 %.2f,2.0 %.2f,2.0 %.2f,0.5 0,0.5" fill="%s"/>'
        % (W, W, x1, x1 - TRAPEZOID_SLOPE, x0 + TRAPEZOID_SLOPE, x0, accent))
    add('  <rect x="0" y="127.5" width="%.2f" height="1.0" fill="%s"/>' % (W, accent))

    # title: name in Bold + "64" in Light, centered; on narrow panels it
    # shrinks to fit, keeping its cap top on the shared line
    segs = spec["title"]
    cap = min(TITLE_CAP, TITLE_CAP * (W - 2 * TITLE_EDGE) / fonts.width(segs, TITLE_CAP))
    add('  <g id="title">')
    text(segs, W / 2, TITLE_TOP + cap, cap, TEXT, "center", "title")
    add('  </g>')

    # jacks: badge (output) or plain label (input) centered under the jack
    for label, x, y, io in spec.get("jacks", []):
        if label is None:
            continue                  # an unlabeled jack (Grid64's 8 x 8)
        cy = y + LABEL_DY
        add('  <!-- %s: %s jack at (%g, %g) -->' % (label, io, x, y))
        if io == "out":
            if fonts.width([(label, "bold")], LABEL_CAP) > BADGE_W - 1.0:
                raise SystemExit("%s: label %s is too wide for its badge" % (name, label))
            add('  <rect x="%.2f" y="%.2f" width="%g" height="%g" rx="%g" fill="%s"/>'
                % (x - BADGE_W / 2, cy - BADGE_H / 2, BADGE_W, BADGE_H, BADGE_RX, TEXT))
            text([(label, "bold")], x, cy + LABEL_CAP / 2, LABEL_CAP, BG, "center", label)
        else:
            text([(label, "bold")], x, cy + LABEL_CAP / 2, LABEL_CAP, TEXT, "center", label)

    # switches (CKSS, 4 x 10 mm): small labels at any side
    for x, y, labels in spec.get("switches", []):
        for side, label in labels.items():
            segs = [(label, "light")]
            if side == "above":
                text(segs, x, y - 6.0, LEGEND_CAP, TEXT, "center", label)
            elif side == "below":
                text(segs, x, y + 7.6, LEGEND_CAP, TEXT, "center", label)
            elif side == "left":
                text(segs, x - 3.6, y + LEGEND_CAP / 2, LEGEND_CAP, TEXT, "right", label)
            elif side == "right":
                text(segs, x + 3.6, y + LEGEND_CAP / 2, LEGEND_CAP, TEXT, "left", label)

    for y in spec.get("separators", []):
        add('  <rect x="3.0" y="%.2f" width="%.2f" height="0.2" fill="%s" opacity="0.35"/>'
            % (y, W - 6.0, TEXT))

    # gesture legend: left-aligned lines, a Bold key then Light text
    legend = spec.get("legend")
    if legend:
        add('  <!-- gesture legend -->')
        y = legend["y"]
        for key, desc in legend["lines"]:
            text([(key + " ", "bold"), (desc, "light")], legend.get("x", 3.0), y,
                 LEGEND_CAP, TEXT, "left",
                 "legend line '%s %s'" % (key, desc))
            y += LEGEND_PITCH

    # domino logo, centered above the bottom rule
    add('  <g transform="translate(%.2f,118.0) scale(0.75)">' % (W / 2 - 12.5 * 0.75 / 2))
    add('    <rect x="0" y="0" width="12.5" height="5.5" rx="1.18" ry="1.2"'
        ' fill="none" stroke="%s" stroke-width="0.5"/>' % TEXT)
    add('    <rect x="6.125" y="0.5" width="0.25" height="4.5" fill="%s"/>' % TEXT)
    for cx, cy in ((2.07, 1.46), (4.19, 4.11), (8.20, 1.46), (10.32, 4.11)):
        add('    <circle cx="%.2f" cy="%.2f" r="0.625" fill="%s"/>' % (cx, cy, TEXT))
    add('  </g>')
    add('</svg>')
    return "\n".join(svg) + "\n"


# ── specs ────────────────────────────────────────────────────────────────────
# jacks: (label, x, y, "out" | "in"), positions = jack centers in mm.

# 6HP two-column output grid, in reading order; P64::twoColumnJack() in
# plugin.hpp places the widgets on the same positions.
COL_L, COL_R, ROW0, ROW_PITCH = 8.6, 21.9, 27.0, 14.0
SEP_Y, BOTTOM_Y, CENTER_6HP = 79.5, 86.0, 3 * HP


def two_columns(labels):
    return [(l, COL_R if i % 2 else COL_L, ROW0 + ROW_PITCH * (i // 2), "out")
            for i, l in enumerate(labels)]


def eight_and_poly(title, labels, legend):
    """8 mono outputs in two columns, POLY centered below a separator."""
    return {
        "hp": 6,
        "title": [(title, "bold"), ("64", "light")],
        "jacks": two_columns(labels) + [("POLY", CENTER_6HP, BOTTOM_Y, "out")],
        "separators": [SEP_Y],
        "legend": {"y": 102.0, "lines": legend},
    }


def one_column(title, labels, legend):
    """4HP: the outputs in one centered column, the legend below them."""
    last = ROW0 + ROW_PITCH * (len(labels) - 1)
    return {
        "hp": 4,
        "title": [(title, "bold"), ("64", "light")],
        "jacks": [(l, CENTER_4HP, ROW0 + ROW_PITCH * i, "out") for i, l in enumerate(labels)],
        "legend": {"x": 1.5, "y": last + LABEL_DY + BADGE_H / 2 + 7.0, "lines": legend},
    }


CENTER_4HP = 2 * HP
GRID_PITCH = 9.6       # Grid64: 8.03 mm jacks need >= 9.53 for 1.5 mm between
T8 = ["T%d" % i for i in range(1, 9)]
PAIRS = ["1–2", "3–4", "5–6", "7–8"]

PANELS = {
    "Step64": {
        "hp": 6,
        "title": [("STEP", "bold"), ("64", "light")],
        "jacks": two_columns(["T%d" % i for i in range(1, 8)])
                 + [("STEP", COL_L, BOTTOM_Y, "out"), ("POLY", COL_R, BOTTOM_Y, "out")],
        "separators": [SEP_Y],
        "legend": {"y": 102.0, "lines": [
            ("ROW 1", "hold + tap: loop"),
            ("ROW 1", "tap: jump"),
            ("ROWS 2–8", "steps"),
        ]},
    },
    "Flin64": eight_and_poly("FLIN", ["G%d" % i for i in range(1, 9)], [
        ("ROWS 1–7", "start, speed"),
        ("ROW 8", "stop"),
        ("HOLD + ROW", "length"),
    ]),
    "Cafe64": eight_and_poly("CAFE", T8, [
        ("1 2 3", "play, edit, length"),
        ("HOLD", "play a rhythm"),
        ("A", "latch"),
    ]),
    "Euclid64": eight_and_poly("EUCL", T8, [
        ("TAP", "fill"),
        ("HOLD + TAP", "length, fill"),
        ("A–H", "mute"),
    ]),
    "Bounce64": eight_and_poly("BNCE", T8, [
        ("ROWS 1–7", "drop"),
        ("ROW 8", "remove"),
        ("A–H", "mute"),
    ]),
    "Meadow64": eight_and_poly("MDW", T8, [
        ("1 2", "play, rules"),
        ("TAP", "row speed"),
        ("A–H", "mute, source"),
    ]),
    "XY64": one_column("XY", ["X", "Y", "TRIG"], [
        ("PAD", "target"),
        ("A–H", "slew"),
    ]),
    "Mlr64": one_column("MLR", ["L", "R", "POLY"], [
        ("PAD", "jump"),
        ("2 PADS", "loop"),
        ("A–D", "choke"),
        ("E–H", "record"),
        ("1 2 3", "pages"),
    ]),
    "Sequencer64": one_column("SEQ", ["CV", "TRIG", "POLY"], [
        ("COLS", "steps"),
        ("HOLD A", "strip"),
    ]),
    "Inertia64": one_column("INRT", ["POS", "VEL", "WRAP"], [
        ("1–4", "push up"),
        ("5–8", "push down"),
        ("A–H", "brake"),
        ("1 2 3", "pages"),
    ]),
    "Keys64": one_column("KEYS", ["PITCH", "GATE", "RTRG"], [
        ("A", "latch"),
        ("B", "arp"),
        ("1 2 3", "pages"),
    ]),
    "Gome64": one_column("GOME", PAIRS, [
        ("ROW 1", "pattern"),
        ("PAD", "root"),
        ("A", "loop"),
        ("B", "record"),
    ]),
    "Rhythm64": one_column("RTM", PAIRS, [
        ("PAD", "play"),
        ("A", "latch"),
        ("B", "punch-in"),
    ]),
    "Life64": {
        "hp": 6,
        "title": [("LIFE", "bold"), ("64", "light")],
        "jacks": two_columns(PAIRS)
                 + [("ROWS", COL_L, 58.0, "out"), ("COLS", COL_R, 58.0, "out"),
                    ("DENS", CENTER_6HP, 72.0, "out")],
        "separators": [51.5],
        "legend": {"y": 87.0, "lines": [
            ("PADS", "toggle cells"),
            ("A", "freeze"), ("B", "clear"), ("C", "randomize"), ("D", "loop"),
            ("E", "recall"), ("F", "save"), ("G", "library"),
        ]},
    },
    "Flood64": {
        "hp": 6,
        "title": [("FLOOD", "bold"), ("64", "light")],
        "jacks": two_columns(["1", "2", "3", "4"])
                 + [("TRIG", COL_L, 58.0, "out"), ("POLY", COL_R, 58.0, "out")],
        "separators": [51.5],
        "legend": {"y": 74.0, "lines": [
            ("PAD", "level"),
            ("1–4", "fader"),
            ("5", "fine zoom"),
            ("A–H", "slew"),
        ]},
    },
    "Buttons64": {
        "hp": 6,
        "title": [("BTTN", "bold"), ("64", "light")],
        "jacks": [(l, COL_R, 30.0 + 20.0 * i, "out") for i, l in enumerate(PAIRS)],
        "switches": [(COL_L, 30.0 + 20.0 * i, {"above": "MOMENT.", "below": "TOGGLE"})
                     for i in range(4)],
    },
    "Grid64": {
        "hp": 16,
        "title": [("GRID", "bold"), ("64", "light")],
        "jacks": [(None, 8 * HP + (c - 3.5) * GRID_PITCH, ROW0 + r * GRID_PITCH, "out")
                  for r in range(8) for c in range(8)],
        "switches": [(8 * HP, 108.0, {"left": "MOMENT.", "right": "TOGGLE"})],
    },
    "Base64": {
        "file": "Base",       # res/Base.svg
        "hp": 8,
        "title": [("BASE", "bold"), ("64", "light")],
        "jacks": [("CLK", 4 * HP - 7.0, 92.0, "in"), ("RST", 4 * HP + 7.0, 92.0, "in"),
                  ("PAGE", 4 * HP - 7.0, 106.0, "out"), ("TRIG", 4 * HP + 7.0, 106.0, "out")],
    },
    "Notes64": {
        "hp": 6, "kind": "companion",
        "title": [("64", "light"), ("NOTES", "bold")],
        "jacks": [(l, COL_R if i % 2 else COL_L, ROW0 + ROW_PITCH * (i // 2), "in")
                  for i, l in enumerate(PAIRS + ["TRN", "CLK"])]
                 + [("V/OCT", COL_L, 72.0, "out"), ("GATE", COL_R, 72.0, "out"),
                    ("RTRG", CENTER_6HP, 86.0, "out")],
        "separators": [65.5],
    },
    "Notes8": {
        "hp": 4, "kind": "companion",
        "title": [("8", "light"), ("NOTES", "bold")],
        "jacks": [("GATE", CENTER_4HP, 27.0, "in"), ("TRN", CENTER_4HP, 41.0, "in"),
                  ("V/OCT", CENTER_4HP, 58.0, "out"), ("GATE", CENTER_4HP, 72.0, "out")],
        "separators": [51.5],
    },
    "Sliders64": eight_and_poly("SLDR", ["COL %d" % i for i in range(1, 9)], [
        ("COLUMNS", "sliders"),
        ("A–H", "slew rate"),
    ]),
}


def kit(name):
    """Kit companion, 4HP: the four cell-gate inputs, then the stereo mix."""
    return {
        "hp": 4, "kind": "companion",
        "title": [("64", "light"), (name, "bold")],
        "jacks": [(l, CENTER_4HP, ROW0 + ROW_PITCH * i, "in") for i, l in enumerate(PAIRS)]
                 + [("L", CENTER_4HP, 86.0, "out"), ("R", CENTER_4HP, 100.0, "out")],
        "separators": [79.5],
    }


for _slug, _name in (("Drums64", "DRUMS"), ("Objects64", "OBJECTS"),
                     ("Grains64", "GRAINS"), ("Micro64", "MICRO")):
    PANELS[_slug] = kit(_name)


def main():
    names = sys.argv[1:] or sorted(PANELS)
    fonts = Fonts()
    for name in names:
        if name not in PANELS:
            raise SystemExit("no spec for %s (have: %s)" % (name, ", ".join(sorted(PANELS))))
        path = os.path.join(ROOT, "res", PANELS[name].get("file", name) + ".svg")
        with open(path, "w") as f:
            f.write(build(name, PANELS[name], fonts))
        print("wrote", os.path.relpath(path, ROOT))


if __name__ == "__main__":
    main()
