#!/usr/bin/env python3
"""Generate pages64 panel SVGs from layout specs (PANELS, below).

Draws the shared panel grammar (CLAUDE.md "Panel structure") for any width:
background, accent trapezoid between the screw zones, title (Montserrat Bold
name + Light "64", cap 4.125 mm, cap top at 7 mm), bottom rule and the domino
logo centered above it. A spec adds the body: jacks with their labels (output
= badge under the jack, input = plain text under the jack), separators, and a
gesture legend. Text is emitted as glyph paths (NanoSVG cannot render <text>),
through gen_title_paths.py's NanoVG-safe pipeline.

Jack positions in a spec are the jack *centers*, the same numbers the widget
code passes to mm2px(Vec(x, y)); keep the two in sync and check the result
with tools/panel_audit/panel_audit.py.

Usage (from the repo root, in the project venv):
    .venv/bin/python tools/gen_panel.py Step64 [...]      # writes res/<Name>.svg
Fonts: Montserrat Bold and Light, vendored in tools/fonts/ (SIL OFL 1.1, see
tools/fonts/OFL.txt); $PAGES64_FONTS overrides the folder.
"""
import os
import sys

from fontTools.ttLib import TTFont

sys.path.insert(0, os.path.dirname(__file__))
from gen_title_paths import glyph_to_svg_d, glyph_advance, text_width  # noqa: E402

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
FONT_DIR = os.environ.get("PAGES64_FONTS", os.path.join(os.path.dirname(__file__), "fonts"))

HP = 5.08
H = 128.5
BG, TEXT = "#1e1e1e", "#d0d0d0"
ACCENT = {"page": "#f26522", "companion": "#22aff2"}

TITLE_CAP, TITLE_BASE = 4.125, 11.125
LABEL_CAP = 2.0
BADGE_W, BADGE_H, BADGE_RX = 11.0, 3.5, 1.0
LABEL_DY = 7.0            # label center below the jack center
LEGEND_CAP, LEGEND_PITCH = 1.6, 3.4
EDGE = 0.8                # text must stay this far inside the panel


class Fonts:
    def __init__(self):
        self.faces = {}
        for weight in ("bold", "light"):
            path = os.path.join(FONT_DIR, "Montserrat-%s.ttf" % weight.capitalize())
            font = TTFont(path)
            self.faces[weight] = (font, font.getGlyphSet(), font.getBestCmap(),
                                  font["OS/2"].sCapHeight)

    def width(self, segments, cap):
        w = 0.0
        for text, weight in segments:
            font, gs, cmap, capu = self.faces[weight]
            w += text_width(font, text, cap / capu)
        return w

    def paths(self, segments, x, baseline, cap, color):
        """Glyph paths for segments [(text, weight)], starting at x."""
        out = []
        for text, weight in segments:
            font, gs, cmap, capu = self.faces[weight]
            scale = cap / capu
            for ch in text:
                if ord(ch) not in cmap:
                    continue
                g = cmap[ord(ch)]
                d = glyph_to_svg_d(gs, g, scale, x, baseline)
                if d:
                    out.append('<path fill="%s" fill-rule="evenodd" d="%s"/>' % (color, d))
                x += glyph_advance(gs, g, scale)
        return out


def build(name, spec, fonts):
    W = spec["hp"] * HP
    accent = ACCENT[spec.get("kind", "page")]
    svg = []
    add = svg.append

    def text(segments, x, baseline, cap, color, align, what):
        w = fonts.width(segments, cap)
        x0 = x - w / 2 if align == "center" else x
        if x0 < EDGE - 1e-6 or x0 + w > W - EDGE + 1e-6:
            raise SystemExit("%s: %s is %.1f mm wide and doesn't fit (x %.1f–%.1f, panel %.2f)"
                             % (name, what, w, x0, x0 + w, W))
        svg.extend("  " + p for p in fonts.paths(segments, x0, baseline, cap, color))

    add('<?xml version="1.0" encoding="UTF-8"?>')
    add('<svg xmlns="http://www.w3.org/2000/svg"')
    add('     width="%gmm" height="%gmm"' % (round(W, 2), H))
    add('     viewBox="0 0 %g %g">' % (round(W, 2), H))
    add('  <!-- generated by tools/gen_panel.py; edit the spec, not this file -->')
    add('  <rect width="%g" height="%g" fill="%s"/>' % (round(W, 2), H, BG))

    # accent trapezoid between the screw zones, and the bottom rule
    x0, x1 = 2 * HP, W - 2 * HP
    add('  <polygon points="0,0 %.2f,0 %.2f,0.5 %.2f,0.5 %.2f,2.0 %.2f,2.0 %.2f,0.5 0,0.5" fill="%s"/>'
        % (W, W, x1, x1 - 2.48, x0 + 2.48, x0, accent))
    add('  <rect x="0" y="127.5" width="%.2f" height="1.0" fill="%s"/>' % (W, accent))

    # title: name in Bold + "64" in Light, centered
    segs = spec["title"]
    add('  <g id="title">')
    text(segs, W / 2, TITLE_BASE, TITLE_CAP, TEXT, "center", "title")
    add('  </g>')

    # jacks: badge (output) or plain label (input) centered under the jack
    for label, x, y, io in spec.get("jacks", []):
        cy = y + LABEL_DY
        add('  <!-- %s: %s jack at (%g, %g) -->' % (label, io, x, y))
        if io == "out":
            add('  <rect x="%.2f" y="%.2f" width="%g" height="%g" rx="%g" fill="%s"/>'
                % (x - BADGE_W / 2, cy - BADGE_H / 2, BADGE_W, BADGE_H, BADGE_RX, TEXT))
            text([(label, "bold")], x, cy + LABEL_CAP / 2, LABEL_CAP, BG, "center", label)
        else:
            text([(label, "bold")], x, cy + LABEL_CAP / 2, LABEL_CAP, TEXT, "center", label)

    for y in spec.get("separators", []):
        add('  <rect x="3.0" y="%.2f" width="%.2f" height="0.2" fill="%s" opacity="0.35"/>'
            % (y, W - 6.0, TEXT))

    # gesture legend: left-aligned lines, a Bold key then Light text
    legend = spec.get("legend")
    if legend:
        add('  <!-- gesture legend -->')
        y = legend["y"]
        for key, desc in legend["lines"]:
            text([(key + " ", "bold"), (desc, "light")], 3.0, y, LEGEND_CAP, TEXT, "left",
                 "legend line '%s %s'" % (key, desc))
            y += LEGEND_PITCH

    # domino logo, centered above the bottom rule
    add('  <g transform="translate(%.2f,118.0) scale(0.75)">' % (W / 2 - 12.5 * 0.75 / 2))
    add('    <rect x="0" y="0" width="12.5" height="5.5" rx="1.18" ry="1.2"'
        ' fill="none" stroke="%s" stroke-width="0.5"/>' % TEXT)
    add('    <rect x="6.125" y="0.5" width="0.25" height="4.5" fill="%s"/>' % TEXT)
    for cx, cy in ((2.07, 1.46), (4.19, 4.11), (8.20, 1.46), (10.32, 4.11)):
        add('    <circle cx="%.2f" cy="%.2f" r="0.625" fill="%s"/>' % (cx, cy, TEXT))
    add('  </g>')
    add('</svg>')
    return "\n".join(svg) + "\n"


# ── specs ────────────────────────────────────────────────────────────────────
# jacks: (label, x, y, "out" | "in"), positions = jack centers in mm.

COL_L, COL_R = 8.6, 21.9          # 6HP two-column grid
PANELS = {
    "Step64": {
        "hp": 6,
        "title": [("STEP", "bold"), ("64", "light")],
        "jacks": [
            ("T1", COL_L, 27, "out"), ("T2", COL_R, 27, "out"),
            ("T3", COL_L, 41, "out"), ("T4", COL_R, 41, "out"),
            ("T5", COL_L, 55, "out"), ("T6", COL_R, 55, "out"),
            ("T7", COL_L, 69, "out"),
            ("STEP", COL_L, 86, "out"), ("POLY", COL_R, 86, "out"),
        ],
        "separators": [79.5],
        "legend": {"y": 102.0, "lines": [
            ("ROW 1", "hold + tap: loop"),
            ("ROW 1", "tap: jump"),
            ("2–8", "toggle steps"),
        ]},
    },
}


def main():
    names = sys.argv[1:] or sorted(PANELS)
    fonts = Fonts()
    for name in names:
        if name not in PANELS:
            raise SystemExit("no spec for %s (have: %s)" % (name, ", ".join(sorted(PANELS))))
        path = os.path.join(ROOT, "res", name + ".svg")
        with open(path, "w") as f:
            f.write(build(name, PANELS[name], fonts))
        print("wrote", os.path.relpath(path, ROOT))


if __name__ == "__main__":
    main()
